// <auto-generated />
using System;
using BrewStore.Vendas.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrewStore.Vendas.Infraestrutura.Migrations
{
    [DbContext(typeof(VendasContext))]
    [Migration("20240929180743_VendasDatabase")]
    partial class VendasDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BrewStore.Vendas.Dominio.PedidoDominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdSituacao")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("BrewStore.Vendas.Dominio.PedidoItemDominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDescontoSazonal")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<decimal?>("PercentualDescontoSazonal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeMinimaDesconto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorDescontoQuantidade")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric(12, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido");

                    b.ToTable("PedidoItems", (string)null);
                });

            modelBuilder.Entity("BrewStore.Vendas.Dominio.PedidoItemDominio", b =>
                {
                    b.HasOne("BrewStore.Vendas.Dominio.PedidoDominio", "Pedido")
                        .WithMany("PedidoItems")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("BrewStore.Vendas.Dominio.PedidoDominio", b =>
                {
                    b.Navigation("PedidoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
